name: Update DB

on:
  schedule:
    - cron: '0 3 * * *' # Ejecutar todos los días a las 0:00 GMT-3

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkear out código
        uses: actions/checkout@v2

      - name: Ejecutar script
        run: |
          pip install -r requirements.txt
          python update_db.py
        env:
          connections.gsheets: ${{ secrets.STREAMLIT_GSHEETS_SECRET }}
